"""add story_arcs table

Revision ID: 09b1eda4fdcd
Revises: 991471b81178
Create Date: 2026-04-01 19:36:34.481495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09b1eda4fdcd'
down_revision: Union[str, Sequence[str], None] = '991471b81178'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_arcs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('series_id', sa.UUID(), nullable=False),
    sa.Column('arc_title', sa.String(length=255), nullable=False),
    sa.Column('start_chapter', sa.Integer(), nullable=False),
    sa.Column('end_chapter', sa.Integer(), nullable=False),
    sa.Column('arc_summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('story_arcs')
    # ### end Alembic commands ###
