"""add living_summary and state_snapshot

Revision ID: 5a00bb02e8ee
Revises: 73fe008728ba
Create Date: 2026-04-07 21:28:04.181795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a00bb02e8ee'
down_revision: Union[str, Sequence[str], None] = '73fe008728ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summaries', sa.Column('state_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('summaries', 'state_snapshot')
    # ### end Alembic commands ###
