"""add chapter url and performance indexes

Revision ID: 5ed3406a5175
Revises: 2a288c66aea6
Create Date: 2026-04-04 19:05:09.029188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ed3406a5175'
down_revision: Union[str, Sequence[str], None] = '2a288c66aea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_processing_status', 'chapter_processing', ['ocr_extracted', 'summary_complete', 'has_error'], unique=False)
    op.create_index('idx_chapter_url', 'chapters', ['url'], unique=False)
    op.create_index('idx_source_lookup', 'series_sources', ['series_id', 'is_active', 'priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_source_lookup', table_name='series_sources')
    op.drop_index('idx_chapter_url', table_name='chapters')
    op.drop_index('idx_processing_status', table_name='chapter_processing')
    # ### end Alembic commands ###
