"""add living_summary to series_metadata

Revision ID: 73fe008728ba
Revises: 30c058997ebe
Create Date: 2026-04-07 21:23:09.235514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73fe008728ba'
down_revision: Union[str, Sequence[str], None] = '30c058997ebe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('series_metadata', sa.Column('living_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('series_metadata', 'living_summary')
    # ### end Alembic commands ###
