"""add is_extracted to chapter_processing

Revision ID: c904be0ca0c5
Revises: 5ed3406a5175
Create Date: 2026-04-07 20:38:29.765370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c904be0ca0c5'
down_revision: Union[str, Sequence[str], None] = '5ed3406a5175'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter_processing', sa.Column('is_extracted', sa.Boolean(), nullable=False, server_default='false'))    
    op.drop_index(op.f('idx_processing_status'), table_name='chapter_processing')
    op.create_index('idx_processing_status', 'chapter_processing', ['is_extracted', 'ocr_extracted', 'summary_complete', 'has_error'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_processing_status', table_name='chapter_processing')
    op.create_index(op.f('idx_processing_status'), 'chapter_processing', ['ocr_extracted', 'summary_complete', 'has_error'], unique=False)
    op.drop_column('chapter_processing', 'is_extracted')
    # ### end Alembic commands ###
